/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assginmentjava3gd;

//import login.login;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import loginform.login;


/**
 *
 * @author bfat
 */
public class view extends javax.swing.JFrame {
    Color DefaultColor,ClickColor;
    private boolean isFormOpen = false;

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        setLocationRelativeTo(null);
         DefaultColor = new Color(153,255,255); // xanh nhạt
         ClickColor = new Color(255, 204, 0); // vàng 
         
         
         // cập nhật màu cho cái panel 
         menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(DefaultColor);
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnshow = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        menuDashboard = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        menuSubject = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        menuPoint = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        menuList = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        menuLogout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        menusetting = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        menuClass = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        menuStudent = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        menuRank = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menuMail = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menuMajor = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        menuSubjectandMajor = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jdesktoppanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(369, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Payment");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Total Earnings");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(593, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText("Dashboard");

        jTextField1.setText("Sreach for student");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Top Performer");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Attendance");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        btnshow.setText("show");
        btnshow.getAccessibleContext().setAccessibleParent(jSeparator1);

        jButton1.setText("jButton1");
        jButton1.getAccessibleContext().setAccessibleParent(jSeparator1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/6771575_building_education_school_university_icon.png"))); // NOI18N
        jLabel1.setText("SCHOOL");

        menuDashboard.setBackground(new java.awt.Color(153, 255, 255));
        menuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashboardMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuDashboardMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9165692_dashboard_graph_icon.png"))); // NOI18N
        jLabel10.setText("Dashboard");

        javax.swing.GroupLayout menuDashboardLayout = new javax.swing.GroupLayout(menuDashboard);
        menuDashboard.setLayout(menuDashboardLayout);
        menuDashboardLayout.setHorizontalGroup(
            menuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDashboardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuDashboardLayout.setVerticalGroup(
            menuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        menuSubject.setBackground(new java.awt.Color(153, 255, 255));
        menuSubject.setPreferredSize(new java.awt.Dimension(137, 43));
        menuSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSubjectMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuSubjectMousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3069185_book_education_learn_school_icon.png"))); // NOI18N
        jLabel16.setText("Subject");

        javax.swing.GroupLayout menuSubjectLayout = new javax.swing.GroupLayout(menuSubject);
        menuSubject.setLayout(menuSubjectLayout);
        menuSubjectLayout.setHorizontalGroup(
            menuSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSubjectLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuSubjectLayout.setVerticalGroup(
            menuSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSubjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        menuPoint.setBackground(new java.awt.Color(153, 255, 255));
        menuPoint.setPreferredSize(new java.awt.Dimension(137, 43));
        menuPoint.setRequestFocusEnabled(false);
        menuPoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPointMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuPointMousePressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8468584_education_test_exam_school_student_icon.png"))); // NOI18N
        jLabel17.setText("Point");

        javax.swing.GroupLayout menuPointLayout = new javax.swing.GroupLayout(menuPoint);
        menuPoint.setLayout(menuPointLayout);
        menuPointLayout.setHorizontalGroup(
            menuPointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPointLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPointLayout.setVerticalGroup(
            menuPointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        menuList.setBackground(new java.awt.Color(153, 255, 255));
        menuList.setPreferredSize(new java.awt.Dimension(137, 43));
        menuList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuListMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuListMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9057073_list_icon.png"))); // NOI18N
        jLabel18.setText("List");

        javax.swing.GroupLayout menuListLayout = new javax.swing.GroupLayout(menuList);
        menuList.setLayout(menuListLayout);
        menuListLayout.setHorizontalGroup(
            menuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuListLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuListLayout.setVerticalGroup(
            menuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        menuLogout.setBackground(new java.awt.Color(153, 255, 255));
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLogoutMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/678146_arrow_exit_log out_right_icon.png"))); // NOI18N
        jLabel9.setText("Logout");

        javax.swing.GroupLayout menuLogoutLayout = new javax.swing.GroupLayout(menuLogout);
        menuLogout.setLayout(menuLogoutLayout);
        menuLogoutLayout.setHorizontalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLogoutLayout.setVerticalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menusetting.setBackground(new java.awt.Color(153, 255, 255));
        menusetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menusettingMousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2799204_management_business_office_setting_success_icon.png"))); // NOI18N
        jLabel19.setText("Setting");

        javax.swing.GroupLayout menusettingLayout = new javax.swing.GroupLayout(menusetting);
        menusetting.setLayout(menusettingLayout);
        menusettingLayout.setHorizontalGroup(
            menusettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusettingLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menusettingLayout.setVerticalGroup(
            menusettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menusettingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        menuClass.setBackground(new java.awt.Color(153, 255, 255));
        menuClass.setPreferredSize(new java.awt.Dimension(137, 43));
        menuClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClassMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuClassMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/20283_class_modules_icon.png"))); // NOI18N
        jLabel7.setText("Class");

        javax.swing.GroupLayout menuClassLayout = new javax.swing.GroupLayout(menuClass);
        menuClass.setLayout(menuClassLayout);
        menuClassLayout.setHorizontalGroup(
            menuClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuClassLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuClassLayout.setVerticalGroup(
            menuClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuClassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        menuStudent.setBackground(new java.awt.Color(153, 255, 255));
        menuStudent.setPreferredSize(new java.awt.Dimension(137, 43));
        menuStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuStudentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuStudentMousePressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/309036_student_education_study_icon.png"))); // NOI18N
        jLabel20.setText("Students");

        javax.swing.GroupLayout menuStudentLayout = new javax.swing.GroupLayout(menuStudent);
        menuStudent.setLayout(menuStudentLayout);
        menuStudentLayout.setHorizontalGroup(
            menuStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuStudentLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuStudentLayout.setVerticalGroup(
            menuStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        menuRank.setBackground(new java.awt.Color(153, 255, 255));
        menuRank.setPreferredSize(new java.awt.Dimension(137, 43));
        menuRank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRankMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuRankMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ranking.png"))); // NOI18N
        jLabel2.setText("Rank");

        javax.swing.GroupLayout menuRankLayout = new javax.swing.GroupLayout(menuRank);
        menuRank.setLayout(menuRankLayout);
        menuRankLayout.setHorizontalGroup(
            menuRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuRankLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuRankLayout.setVerticalGroup(
            menuRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuRankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuMail.setBackground(new java.awt.Color(153, 255, 255));
        menuMail.setPreferredSize(new java.awt.Dimension(137, 43));
        menuMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMailMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuMailMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mail.png"))); // NOI18N
        jLabel6.setText("Send Email");

        javax.swing.GroupLayout menuMailLayout = new javax.swing.GroupLayout(menuMail);
        menuMail.setLayout(menuMailLayout);
        menuMailLayout.setHorizontalGroup(
            menuMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMailLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuMailLayout.setVerticalGroup(
            menuMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuMajor.setBackground(new java.awt.Color(153, 255, 255));
        menuMajor.setPreferredSize(new java.awt.Dimension(137, 43));
        menuMajor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMajorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuMajorMousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2620524_cv_employee_job_seeker_unemployee_icon.png"))); // NOI18N
        jLabel21.setText("Major");

        javax.swing.GroupLayout menuMajorLayout = new javax.swing.GroupLayout(menuMajor);
        menuMajor.setLayout(menuMajorLayout);
        menuMajorLayout.setHorizontalGroup(
            menuMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMajorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuMajorLayout.setVerticalGroup(
            menuMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMajorLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        menuSubjectandMajor.setBackground(new java.awt.Color(153, 255, 255));
        menuSubjectandMajor.setPreferredSize(new java.awt.Dimension(137, 43));
        menuSubjectandMajor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSubjectandMajorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuSubjectandMajorMousePressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setText("Subject and Major");

        javax.swing.GroupLayout menuSubjectandMajorLayout = new javax.swing.GroupLayout(menuSubjectandMajor);
        menuSubjectandMajor.setLayout(menuSubjectandMajorLayout);
        menuSubjectandMajorLayout.setHorizontalGroup(
            menuSubjectandMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuSubjectandMajorLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(19, 19, 19))
        );
        menuSubjectandMajorLayout.setVerticalGroup(
            menuSubjectandMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSubjectandMajorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(menusetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuSubject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addComponent(menuPoint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addComponent(menuList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addComponent(menuLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuClass, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addComponent(menuStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addComponent(menuRank, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addComponent(menuMail, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addComponent(menuMajor, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addComponent(menuSubjectandMajor, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuSubjectandMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menusetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jdesktoppanel.setPreferredSize(new java.awt.Dimension(1098, 300));

        javax.swing.GroupLayout jdesktoppanelLayout = new javax.swing.GroupLayout(jdesktoppanel);
        jdesktoppanel.setLayout(jdesktoppanelLayout);
        jdesktoppanelLayout.setHorizontalGroup(
            jdesktoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1102, Short.MAX_VALUE)
        );
        jdesktoppanelLayout.setVerticalGroup(
            jdesktoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(153, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Search :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jdesktoppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jdesktoppanel, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void menuDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMousePressed
         menuDashboard.setBackground(ClickColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(DefaultColor);
    }//GEN-LAST:event_menuDashboardMousePressed

    private void menuStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStudentMousePressed
        menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(ClickColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(DefaultColor);
    }//GEN-LAST:event_menuStudentMousePressed

    private void menuClassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClassMousePressed
        menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(ClickColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(DefaultColor);
    }//GEN-LAST:event_menuClassMousePressed

    private void menuSubjectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSubjectMousePressed
        menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(ClickColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(DefaultColor);
    }//GEN-LAST:event_menuSubjectMousePressed

    private void menuPointMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPointMousePressed
        menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(ClickColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(DefaultColor);
    }//GEN-LAST:event_menuPointMousePressed

    private void menuListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuListMousePressed
        menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(ClickColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(DefaultColor);
    }//GEN-LAST:event_menuListMousePressed

    private void menuStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStudentMouseClicked
       student2 st = new student2();
        jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
        jdesktoppanel.add(st);  // Thêm đối tượng st
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        st.setVisible(true);  // Đảm bảo đối tượng st là visible
    }//GEN-LAST:event_menuStudentMouseClicked

    private void menuClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClassMouseClicked
        class2 cl = new class2(); // cái này là jframe 
        jdesktoppanel.removeAll(); 
        jdesktoppanel.add(cl);  // Thêm đối tượng po
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        cl.setVisible(true);
    }//GEN-LAST:event_menuClassMouseClicked

    private void menuSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSubjectMouseClicked
        subject2 sb = new subject2(); // cái này là jframe 
        jdesktoppanel.removeAll(); 
        jdesktoppanel.add(sb);  // Thêm đối tượng po
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        sb.setVisible(true);
    }//GEN-LAST:event_menuSubjectMouseClicked

    private void menuPointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPointMouseClicked
        point2 po = new point2(); // cái này là jframe 
        jdesktoppanel.removeAll(); 
        jdesktoppanel.add(po);  // Thêm đối tượng po
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        po.setVisible(true);

// Kiểm tra nếu form sb chưa mở
//        if (sb == null || !sb.isVisible()) {
//        sb = new subject2(); // Tạo mới đối tượng subject2
//        jdesktoppanel.add(sb); // Thêm đối tượng sb vào DesktopPanel
//        jdesktoppanel.revalidate(); // Cập nhật lại giao diện
//        jdesktoppanel.repaint(); // Vẽ lại giao diện
//        sb.setVisible(true); // Hiển thị form
//        isFormOpen = true;
    }//GEN-LAST:event_menuPointMouseClicked

    private void menuListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuListMouseClicked
        list2 lt = new list2();
        jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
        jdesktoppanel.add(lt);  // Thêm đối tượng lt
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        lt.setVisible(true);
    }//GEN-LAST:event_menuListMouseClicked

    private void menusettingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menusettingMousePressed
        menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(ClickColor);
         menuLogout.setBackground(DefaultColor);
       
    }//GEN-LAST:event_menusettingMousePressed

    private void menuLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMousePressed
         menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(ClickColor);
    }//GEN-LAST:event_menuLogoutMousePressed

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        login login = new login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMouseClicked
        Dashboard2 das = new Dashboard2();
        jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
        jdesktoppanel.add(das);  // Thêm đối tượng st
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        das.setVisible(true);
        
    }//GEN-LAST:event_menuDashboardMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void menuRankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRankMouseClicked
        Rank2 rank = new Rank2();
        jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
        jdesktoppanel.add(rank);  // Thêm đối tượng rank
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        rank.setVisible(true);
    }//GEN-LAST:event_menuRankMouseClicked

    private void menuMailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMailMouseClicked
        SendEmail send = new SendEmail();
        jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
        jdesktoppanel.add(send);  // Thêm đối tượng send
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        send.setVisible(true);
    }//GEN-LAST:event_menuMailMouseClicked

    private void menuRankMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRankMousePressed
         menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(ClickColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(DefaultColor);
    }//GEN-LAST:event_menuRankMousePressed

    private void menuMailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMailMousePressed
         menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(ClickColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(DefaultColor);
    }//GEN-LAST:event_menuMailMousePressed

    private void menuMajorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMajorMouseClicked
        Major2 ma = new Major2();
        jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
        jdesktoppanel.add(ma);  // Thêm đối tượng ma
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        ma.setVisible(true);
    }//GEN-LAST:event_menuMajorMouseClicked

    private void menuSubjectandMajorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSubjectandMajorMouseClicked
        SubjectandMajor2 sbma = new SubjectandMajor2();
        jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
        jdesktoppanel.add(sbma);  // Thêm đối tượng sbma
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        sbma.setVisible(true);
    }//GEN-LAST:event_menuSubjectandMajorMouseClicked

    private void menuMajorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMajorMousePressed
         menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(ClickColor);
         menuSubjectandMajor.setBackground(DefaultColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(DefaultColor);
    }//GEN-LAST:event_menuMajorMousePressed

    private void menuSubjectandMajorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSubjectandMajorMousePressed
         menuDashboard.setBackground(DefaultColor);
         menuClass.setBackground(DefaultColor);
         menuSubject.setBackground(DefaultColor);
         menuMajor.setBackground(DefaultColor);
         menuSubjectandMajor.setBackground(ClickColor);
         menuStudent.setBackground(DefaultColor);
         menuPoint.setBackground(DefaultColor);
         menuList.setBackground(DefaultColor);
         menuRank.setBackground(DefaultColor);
         menuMail.setBackground(DefaultColor);
         menusetting.setBackground(DefaultColor);
         menuLogout.setBackground(DefaultColor);
    }//GEN-LAST:event_menuSubjectandMajorMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnshow;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel jdesktoppanel;
    private javax.swing.JPanel menuClass;
    private javax.swing.JPanel menuDashboard;
    private javax.swing.JPanel menuList;
    private javax.swing.JPanel menuLogout;
    private javax.swing.JPanel menuMail;
    private javax.swing.JPanel menuMajor;
    private javax.swing.JPanel menuPoint;
    private javax.swing.JPanel menuRank;
    private javax.swing.JPanel menuStudent;
    private javax.swing.JPanel menuSubject;
    private javax.swing.JPanel menuSubjectandMajor;
    private javax.swing.JPanel menusetting;
    // End of variables declaration//GEN-END:variables
}
